# Generated by Django 2.1.5 on 2019-07-16 14:26

from django.db import migrations, models
import gamemaster.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=gamemaster.helpers.generateToken, max_length=6)),
            ],
        ),
    ]
