# Generated by Django 2.1.5 on 2019-07-16 14:28

from django.db import migrations, models
import gamemaster.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0002_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(default=gamemaster.helpers.generateToken, max_length=6, primary_key=True, serialize=False),
        ),
    ]
