# Generated by Django 2.1.5 on 2019-03-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameResults',
            new_name='GameResult',
        ),
    ]
