# Generated by Django 2.1.5 on 2019-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20190313_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
