# Generated by Django 2.1.5 on 2019-04-19 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20190419_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('value', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
